apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ing
  namespace: petclinic
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: k8-petclinic.joshmc.xyz     
    http:
      paths:
      - path: /
        backend:
          serviceName: petclinic-service
          servicePort: http
  tls:
  - hosts:
      - k8-petclinic.joshmc.xyz
    secretName: petclinic-secret

